package:
    name: dime2
    version: latest

source:
    git_url: https://github.com/TheHashTableSlasher/dime2.git

requirements:
    build:
        - git
        - make

    host:
        - {{ compiler('c') }}
        - openssl
        - zlib
        - python
        - setuptools

    run:
        - python
        - numpy

about:
  home: https://github.com/TheHashTableSlasher/dime2
