package:
    name: dime-server
    version: "0.0.1"

source:
    path: ./dime/server

requirements:
    build:
        - make

    host:
        - {{ compiler('c') }}
        - python
        - autoconf
        - libtool
        - setuptools
        - zlib
        - openssl
        - jansson

    run:
        - python
        - zlib
        - openssl
        - jansson

about:
    home: https://github.com/TheHashTableSlasher/dime2
