package:
  name: dime2
  version: latest

source:
  git_url: https://github.com/TheHashTableSlasher/dime2.git

requirements:
  build:
    - setuptools
    - {{ compiler('c') }}
    - make

  host:
    - python
    - jansson
    - openssl
    - zlib

  run:
    - python

test:
  imports:
    -

about:
  home: https://github.com/TheHashTableSlasher/dime2
