package:
    name: dime
    version: "0.0.1"

source:
    path: .

requirements:
    build:
        - make
        - cmake
        - python
        - setuptools
        - pip

    host:
        - {{ compiler('c') }}
        - setuptools

    run:
        - python
        - zlib
        - openssl
        - jansson
        - dime-server
        - dime-client

about:
    home: https://github.com/CURENT/dime
    license: GPL-3.0
    summary: LTB DiME - Distributed Monitoring Environment for CURENT Large-scale Testbed

extra:
  recipe-maintainers:
    - Jinning Wang <jinninggm@gmail.com>

# package both client and server
outputs:
  - name: dime-client
    files:
      - dime/client/*
  - name: dime-server
    files:
      - dime/server/*
