package:
    name: dime2
    version: "0.0.1"

source:
    path: .

requirements:
    build:
        - make

    host:
        - {{ compiler('c') }}
        - python
        - setuptools
        - zlib
        - openssl
        - jansson

    run:
        - python
        - zlib
        - openssl
        - jansson

about:
    home: https://github.com/TheHashTableSlasher/dime2
